"""Generate assets/brand/dhoa-mark.svg — the association's emblem.

The only surviving copy of the mark is the letterhead on a fax-quality scan
(the RV lot notice of August 2025). Rather than trace that scan — which would
carry all its noise — the geometry below was measured from it at 1200 dpi and
is redrawn cleanly here.

How the numbers were obtained:

  * The fourteen fruit are centroids. The bitmap was eroded with a 22px disc
    until only the discs survived and the thin trunk and lines vanished, then
    connected-component analysis gave each centre.
  * The ridge and hill lines were sampled column by column across the frame,
    recording every run of ink. The ridge turned out to be a THIN line with
    sparse stipple scattered beneath it, not a thick filled band — an earlier
    version of this drawing got that wrong.
  * Everything is expressed in a 100 x 122 unit space, which is the aspect
    ratio of the original frame (776 x 948 px).

Run:  python3 tools/render-dhoa-mark.py
"""

import random
from pathlib import Path

random.seed(11)

OUT = Path(__file__).resolve().parent.parent / "assets/brand/dhoa-mark.svg"

# ── Measured control points (x, y) in the 100 x 122 unit space ──────────────

# Crest of the far ridge. Apex sits a little right of centre, under the sun.
#
# These are CENTRE-LINE values. The column scan reports the top of each ink
# run, and the ridge run is 2.9 units thick at the left thinning to 1.9 at the
# right — so half that thickness is added back here. Stroking the run tops
# directly put the whole ridge about 1.3 units too high, which was the last
# systematic error against the scan.
RIDGE = [(0, 46.5), (11.1, 43.3), (22.9, 39.4), (34.8, 35.7), (46.6, 31.4),
         (55.0, 30.6), (64.4, 34.2), (76.3, 38.0), (88.1, 41.7), (100, 46.6)]

# Two nested hills behind the tree, both peaking left of the ridge apex. They
# very nearly touch in the middle — at x=34.8 the scan shows a single 3-unit
# run where the two lines overlap — and separate toward the frame edges. An
# earlier version collapsed them into one line, which is what made the lower
# right of the drawing look empty against the original.
HILL_FAR = [(0, 56.0), (11.1, 53.3), (22.9, 48.5), (34.8, 45.0), (46.0, 43.8),
            (58.5, 47.0), (70.4, 47.1), (82.2, 47.9), (94.1, 51.0), (100, 52.4)]

HILL_NEAR = [(0, 61.5), (11.1, 58.2), (22.9, 52.5), (34.8, 46.8), (44.0, 45.4),
             (58.5, 49.5), (70.4, 54.3), (82.2, 59.8), (94.1, 64.9), (100, 67.5)]

# Fourteen fruit, in four staggered columns.
FRUIT = [(44.6, 56.5), (60.0, 63.2), (33.6, 65.4), (44.6, 70.1),
         (72.9, 70.4), (60.8, 75.4), (33.3, 79.4), (72.8, 81.2),
         (44.5, 83.5), (61.4, 88.6), (33.4, 91.7), (73.3, 92.9),
         (44.5, 95.3), (61.5, 99.9)]
FRUIT_R = 4.95

SUN = (51.6, 26.0, 6.9)          # cx, cy, r (centre-line of the ring)


def smooth(points):
    """A path through the points using Catmull-Rom converted to cubic Bezier —
    the ridge and hill are surveyed curves, not arcs, so fit them properly."""
    p = [points[0]] + list(points) + [points[-1]]
    d = f"M{points[0][0]:.1f} {points[0][1]:.1f}"
    for i in range(1, len(p) - 2):
        p0, p1, p2, p3 = p[i - 1], p[i], p[i + 1], p[i + 2]
        c1 = (p1[0] + (p2[0] - p0[0]) / 6, p1[1] + (p2[1] - p0[1]) / 6)
        c2 = (p2[0] - (p3[0] - p1[0]) / 6, p2[1] - (p3[1] - p1[1]) / 6)
        d += (f" C{c1[0]:.1f} {c1[1]:.1f}, {c2[0]:.1f} {c2[1]:.1f},"
              f" {p2[0]:.1f} {p2[1]:.1f}")
    return d


def interp(points, x):
    for i in range(len(points) - 1):
        x0, y0 = points[i]
        x1, y1 = points[i + 1]
        if x0 <= x <= x1:
            return y0 + (y1 - y0) * (x - x0) / (x1 - x0)
    return points[-1][1]


# ── Stipple: sparse specks between the ridge line and the hill line ────────
# Denser on the left, where the gap is widest and the original is busiest.
dots = []
x = 3.0
while x < 97:
    top = interp(RIDGE, x) + 2.4
    bot = interp(HILL_FAR, x) - 1.8
    gap = bot - top
    if gap > 2:
        density = 0.75 if x < 50 else 0.45      # the original thins to the right
        n = max(0, int(gap / 3.4 * density * 2))
        for _ in range(n):
            yy = random.uniform(top, bot)
            xx = x + random.uniform(-1.1, 1.1)
            dots.append((round(xx, 1), round(yy, 1)))
    x += 3.1

speck_rows = []
for i in range(0, len(dots), 6):
    speck_rows.append("      " + "".join(
        f'<circle cx="{cx}" cy="{cy}" r="0.7"/>' for cx, cy in dots[i:i + 6]))
specks = "\n".join(speck_rows)

fruit_rows = "\n".join(
    f'      <circle cx="{cx}" cy="{cy}" r="{FRUIT_R}"/>' for cx, cy in FRUIT)

svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 122" class="mark"
     role="img" aria-label="Discovery Homeowners Association">
  <!--
    GENERATED by tools/render-dhoa-mark.py — edit that, not this file.

    The association's emblem, redrawn from measurements of the only surviving
    copy (a fax-quality letterhead scan) rather than traced from it. A ring sun
    at the crest of a stippled ridge, a nearer hill crossing behind, and an
    orchard tree of fourteen fruit in four staggered columns — apt for a
    neighborhood laid out over a farm in 1972.

    Drawn with currentColor so it inherits its surroundings and works in both
    light and dark themes.
  -->
  <defs>
    <clipPath id="mark-interior">
      <rect x="5.2" y="5.2" width="89.6" height="111.6" rx="4"/>
    </clipPath>
  </defs>

  <g clip-path="url(#mark-interior)">
    <!-- Ploughed-field stipple between the two ridges. -->
    <g class="mark__texture" fill="currentColor">
{specks}
    </g>

    <!-- The far ridge, and the nearer hill behind the tree. -->
    <path class="mark__ridge" fill="none" stroke="currentColor" stroke-width="2.1"
          stroke-linecap="round" stroke-linejoin="round"
          d="{smooth(RIDGE)}"/>
    <path class="mark__hill" fill="none" stroke="currentColor" stroke-width="1.6"
          stroke-linecap="round" stroke-linejoin="round"
          d="{smooth(HILL_FAR)}"/>
    <path class="mark__hill" fill="none" stroke="currentColor" stroke-width="1.6"
          stroke-linecap="round" stroke-linejoin="round"
          d="{smooth(HILL_NEAR)}"/>

    <!-- Sun: a ring sitting at the crest. -->
    <circle class="mark__sun" cx="{SUN[0]}" cy="{SUN[1]}" r="{SUN[2]}"
            fill="none" stroke="currentColor" stroke-width="1.9"/>

    <!-- Tree: trunk to the ground, with two short stubs. -->
    <path class="mark__trunk" fill="none" stroke="currentColor" stroke-width="2.3"
          stroke-linecap="round"
          d="M53.0 118 C 52.4 100, 53.2 84, 52.5 68 C 52.2 61, 53.0 56, 53.7 51.5"/>
    <path class="mark__trunk" fill="none" stroke="currentColor" stroke-width="1.5"
          stroke-linecap="round"
          d="M52.6 76 L 48.0 71.8 M52.5 66 L 57.2 62.6"/>

    <!-- Fourteen fruit. -->
    <g class="mark__fruit" fill="currentColor">
{fruit_rows}
    </g>
  </g>

  <!-- Frame last, so it sits cleanly over anything reaching the edge. -->
  <rect class="mark__frame" x="2.6" y="2.6" width="94.8" height="116.8" rx="5.5"
        fill="none" stroke="currentColor" stroke-width="5.2"/>
</svg>
'''

OUT.write_text(svg)
print(f"{OUT.relative_to(OUT.parents[1])}: {len(svg)/1024:.1f} KB, "
      f"{len(dots)} specks, {len(FRUIT)} fruit")
